# .github/workflows/wiki-sync.yml
name: Sync Wiki
on:
  push:
    branches: [main]
    paths:
      - 'docs/wiki/**'
      - .github/workflows/wiki-sync.yml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Wiki
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        GH_PAT: ${{ secrets.WIKI_SYNC }}
        ACTION_MAIL: sritchie99@mail.com
        ACTION_NAME: rimuadmin
        OWNER: rimuadmin
        REPO_NAME: ProtoFlex