# .github/workflows/wiki-sync.yml
name: Sync Wiki
on:
  push:
    branches: [main]
    paths:
      - 'docs/wiki/**'
      - .github/workflows/wiki-sync.yml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Andrew-Chen-Wang/github-wiki-action@v4