# .github/workflows/wiki-sync.yml
name: Sync Wiki
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - .github/workflows/wiki-sync.yml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: sritchie99@mail.com

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: docs
          destination: wiki
          token: ${{ secrets.WIKI_SYNC }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}    

